name: CI

on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      # Add a step to copy the service account key from GitHub Secrets to the Firebase folder
      - name: Copy service account key
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: |
          mkdir -p Firebase && echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > Firebase/serviceAccountKey.json

      - name: Run a one-line script
        run: |
          echo Hello raspberry!
          ls
